### ISSUE TITLE
Dockerfile of Flask returns and error

### ISSUE THREAD

**Issue by DanBrown47** [AryanSh98/flask-docker-opencv-nginx#1]
```shell
Step 4/6 : RUN apt-update
 ---> Running in 52d282a91eaf
/bin/sh: 1: apt-update: not found
The command '/bin/sh -c apt-update' returned a non-zero code: 127
```

The image is python:3
apt is not a part of python

**Comment by AryanSh98** [comment]
> ```shell
> Step 4/6 : RUN apt-update
>  ---> Running in 52d282a91eaf
> /bin/sh: 1: apt-update: not found
> The command '/bin/sh -c apt-update' returned a non-zero code: 127
> ```
> 
> The image is python:3
> apt is not a part of python

Hello @DanBrown47 , Thanks for your feedback.
Your issue is probably caused by the fact that your python:3 image is not Ubuntu-based,(Alpine-based perhaps) so the command `apt-update` doesn't exist. Did you have a python:3 image already?

**Comment by DanBrown47** [comment]
As per the docker file in your repo it pulls python:3 and is alpine based. The docker would also work without the update command

**Comment by AryanSh98** [comment]
> As per the docker file in your repo it pulls python:3 and is alpine based. The docker would also work without the update command

You're right. I changed the Dockerfile code so that it pulls an Ubuntu-based Python3 image. Let me know if the issue is resolved.
